#ifndef MYTYPES_H
#define MYTYPES_H


#define BLOCKTILE_M 64
#define BLOCKTILE_N 64
#define BLOCKTILE_K 32
#define THREADTILE_M (BLOCKTILE_M/BLOCKDIM_Y)
#define THREADTILE_N (BLOCKTILE_N/BLOCKDIM_X)

#define BY BLOCKDIM_Y
#define BX BLOCKDIM_X
#define BK BLOCKTILE_K
#define BM BLOCKTILE_M
#define BN BLOCKTILE_N
#define TM THREADTILE_M
#define TN THREADTILE_N


#endif
